[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false